global:
  network: mainnet
  service:
    ports:
      rpc: 8332

secrets:
  create: true

bitcoin:
  # Core Settings
  serverEnabled: 1
  dbCrashRatio: 0.0001
  txindexEnabled: 1
  printtoconsoleEnabled: 1
  rpcUser: rpcuser
  rpcBind: "0.0.0.0"
  rpcAllowIP: "0.0.0.0/0"

  # ZMQ Settings
  zmqPubRawTx: "tcp://0.0.0.0:8431"
  zmqPubRawBlock: "tcp://0.0.0.0:8432"
  zmqPubHashBlock: "tcp://0.0.0.0:8433"

  # Performance Tuning (adjust based on available resources)
  dbCache: 4096  # 4 GB DB cache
  maxConnections: 80  # Reasonable upper limit
  rpcWorkQueue: 1000  # Large RPC queue
  maxMempool: 600  # 600 MB mempool
  blockReconstructionExtraTxn: 10000

  # OCEAN Policy Compliance
  dataCarrierSize: 1  # Enable OP_RETURN (OCEAN requires)
  acceptNonStdTxn: 0  # Default
  acceptNonStdDataCarrier: 0  # Default
  dataCarrierCost: 1  # Default
  dataCarrierSizeLimit: 42  # Default
  bytesPerSigop: 20  # Default
  bytesPerSigopStrict: 20  # Default
  maxScriptSize: 1650  # Default
  mempoolFullRbf: 1  # Default
  mempoolReplacement: "fee,-optin"  # Enforce full RBF (OCEAN requires)
  minRelayTxFee: 0.00001  # Default
  permitBareMultisig: 0  # Default
  permitBarePubkey: 0  # Default
  rejectParasites: 1  # Default
  spkReuse: "allow"  # Default

  # Mining Block Template
  datumHost: 127.0.0.1
  datumPort: 8080
  blockMaxSize: 3985000  # OCEAN override
  blockMaxWeight: 3985000  # OCEAN override
  blockMinTxFee: 0.00001  # Default
  blockPrioritySize: 0  # OCEAN override

  # Reindex flags
  reindex: 0  # Set to 1 to reindex blocks
  reindexChainstate: 0  # Set to 1 to reindex chainstate (only utxo set, not txindex)

replicaCount: 1

terminationGracePeriodSeconds: 10

priorityClassName: ""

image:
  repository: ghcr.io/cosmicrocks/knots
  pullPolicy: Always
  tag: "28.1.knots20250305"

metrics:
  podMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 20s

extraInitContainers: []
sidecarContainers: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "bitcoin"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  # limits:
  #   memory: 16Gi
  # requests:
  #   cpu: 1000m
  #   memory: 16Gi

persistence:
  enabled: false
  storageClass: ""
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 900Gi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

podLabels:
  app: bitcoin

service:
  type: ClusterIP
  ports:
    zmqpubrawtx: 8431
    zmqpubrawblock: 8432
    zmqpubhashblock: 8433
    p2p: 8333
    metrics: 9223

datum:
  enabled: true
  image:
    repository: ghcr.io/cosmicrocks/datum
    pullPolicy: Always
    tag: "v0.3.1beta"
  service:
    stratumPort: 23334  # Stratum protocol port
    apiPort: 8080      # API port

  # Bitcoin RPC connection configuration
  bitcoin:
    rpcHost: "localhost:8332"  # Bitcoin RPC host within the pod
    rpcuser: "rpcuser"         # Bitcoin RPC username

  # Bitcoin daemon-specific settings
  bitcoind:
    workUpdateSeconds: 40      # How often to update mining work
    notifyFallback: true       # Use fallback notification mechanism

  # Stratum server configuration
  stratum:
    maxClientsPerThread: 128   # Maximum clients per thread
    maxThreads: 8              # Maximum number of threads
    maxClients: 1024           # Maximum number of clients
    vardiffMin: 16384          # Minimum variable difficulty
    vardiffTargetSharesMin: 8  # Target shares minimum for vardiff
    vardiffQuickdiffCount: 8   # Quickdiff count
    vardiffQuickdiffDelta: 8   # Quickdiff delta
    shareStaleSeconds: 120     # Seconds after which shares are considered stale
    fingerprintMiners: true    # Enable miner fingerprinting
    idleTimeoutNoSubscribe: 15 # Idle timeout for connections without subscribe
    idleTimeoutNoShares: 7200  # Idle timeout for connections without shares
    idleTimeoutMaxLastWork: 0  # Maximum time since last work (0 = disabled)

  # Mining configuration
  mining:
    address: "bc1q676lj6ttgpu7p25uk3ex2thyxdrvralct2upl4"  # Mining reward address
    coinbaseTagPrimary: "DATUM Gateway"                   # Primary coinbase tag
    coinbaseTagSecondary: "Cosmic Rocks"                  # Secondary coinbase tag
    coinbaseUniqueId: 32359                               # Unique ID for coinbase
    saveSubmitblocksDir: ""                               # Directory to save submitted blocks (empty = disabled)
    poolHost: "datum-beta1.mine.ocean.xyz"                # Pool host for mining (empty for solo mining)

  # API configuration
  api:
    adminPassword: "admin"                                # Admin password for API
    extraBlockSubmissionsUrls: "[]"                       # Extra URLs to submit blocks to (JSON array as string)

  # Logging configuration
  logger:
    logToConsole: true                                    # Log to console
    logToStderr: false                                    # Log to stderr
    logToFile: false                                      # Log to file
    logFile: ""                                           # Log file path (empty = disabled)
    logRotateDaily: true                                  # Rotate logs daily
    logCallingFunction: true                              # Log calling functions
    logLevelConsole: 2                                    # Console log level
    logLevelFile: 1                                       # File log level

  # Pool settings
  pool:
    port: 28915                                           # Pool port
    pubkey: "f21f2f0ef0aa1970468f22bad9bb7f4535146f8e4a8f646bebc93da3d89b1406f40d032f09a417d94dc068055df654937922d2c89522e3e8f6f0e649de473003"  # Pool public key
    passWorkers: true                                     # Pass worker information
    passFullUsers: true                                   # Pass full user information
    alwaysPaySelf: true                                   # Always pay self
    pooledMiningOnly: false                               # Pooled mining only
    protocolGlobalTimeout: 60                             # Protocol global timeout

  # Resources for the Datum container
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

  persistence:
    enabled: true
    # existingClaim: ""
    storageClass: {}
    accessMode: ReadWriteOncePod
    size: 1Gi
