global:
  network: mainnet
  service:
    ports:
      rpc: 8332

secrets:
  create: true

command: []

bitcoin:
  # Core Settings
  serverEnabled: 1
  dbCrashRatio: 0.0001
  txindexEnabled: 1
  printtoconsoleEnabled: 1
  rpcUser: rpcuser
  rpcBind: "0.0.0.0"
  rpcAllowIP: "0.0.0.0/0"

  # ZMQ Settings
  zmqPubRawTx: "tcp://0.0.0.0:8431"
  zmqPubRawBlock: "tcp://0.0.0.0:8432"
  zmqPubHashBlock: "tcp://0.0.0.0:8433"

  # Performance Tuning (adjust based on available resources)
  dbCache: 4096  # 4 GB DB cache
  maxConnections: 80  # Reasonable upper limit
  rpcWorkQueue: 1000  # Large RPC queue
  maxMempool: 600  # 600 MB mempool
  blockReconstructionExtraTxn: 10000

  # OCEAN Policy Compliance
  dataCarrierSize: 1  # Enable OP_RETURN (OCEAN requires)
  acceptNonStdTxn: 0  # Default
  acceptNonStdDataCarrier: 0  # Default
  dataCarrierCost: 1  # Default
  dataCarrierSizeLimit: 42  # Default
  bytesPerSigop: 20  # Default
  bytesPerSigopStrict: 20  # Default
  maxScriptSize: 1650  # Default
  mempoolFullRbf: 1  # Default
  mempoolReplacement: "fee,-optin"  # Enforce full RBF (OCEAN requires)
  minRelayTxFee: 0.00001  # Default
  permitBareMultisig: 0  # Default
  permitBarePubkey: 0  # Default
  rejectParasites: 1  # Default
  spkReuse: "allow"  # Default

  # Mining Block Template
  blockMaxSize: 3985000  # OCEAN override
  blockMaxWeight: 3985000  # OCEAN override
  blockMinTxFee: 0.00001  # Default
  blockPrioritySize: 0  # OCEAN override

  # Reindex flags
  reindex: 0  # Set to 1 to reindex blocks
  reindexChainstate: 0  # Set to 1 to reindex chainstate (only utxo set, not txindex)

replicaCount: 1

terminationGracePeriodSeconds: 10

priorityClassName: ""

image:
  repository: ghcr.io/cosmicrocks/knots
  pullPolicy: Always
  tag: "28.1.knots20250305"

metrics:
  podMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 20s

extraInitContainers: []
sidecarContainers: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "bitcoin"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

resources:
  # limits:
  #   memory: 16Gi
  # requests:
  #   cpu: 1000m
  #   memory: 16Gi

persistence:
  enabled: true  # Enable persistence by default for StatefulSet
  storageClass: ""
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 900Gi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

podLabels:
  app: bitcoin

service:
  type: ClusterIP
  ports:
    zmqpubrawtx: 8431
    zmqpubrawblock: 8432
    zmqpubhashblock: 8433
    p2p: 8333
    metrics: 9223


