apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
{{- end }}
  selector:
    matchLabels:
      {{- include "bitcoin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      priorityClassName: {{ .Values.priorityClassName | default "" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitcoin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.extraInitContainers }}
      {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 8 }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "bitcoin-cli stop"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Core Settings
            - name: SERVER_ENABLED
              value: {{ .Values.bitcoin.serverEnabled | default "1" | quote }}
            - name: TXINDEX_ENABLED
              value: {{ .Values.bitcoin.txindexEnabled | default "1" | quote }}
            - name: PRINTTOCONSOLE_ENABLED
              value: {{ .Values.bitcoin.printtoconsoleEnabled | default "1" | quote }}
            - name: RPC_USER
              value: {{ .Values.bitcoin.rpcUser | default "rpcuser" }}
            - name: RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
                  key: password
            - name: RPC_BIND
              value: {{ .Values.bitcoin.rpcBind | default "0.0.0.0" }}
            - name: RPC_PORT
              value: {{ .Values.global.service.ports.rpc | default "8332" | quote }}
            - name: RPC_ALLOW_IP
              value: {{ .Values.bitcoin.rpcAllowIP | default "0.0.0.0/0" }}

            # ZMQ Settings
            - name: ZMQ_PUB_RAW_TX
              value: {{ .Values.bitcoin.zmqPubRawTx | default "tcp://0.0.0.0:8431" }}
            - name: ZMQ_PUB_RAW_BLOCK
              value: {{ .Values.bitcoin.zmqPubRawBlock | default "tcp://0.0.0.0:8432" }}
            - name: ZMQ_PUB_HASH_BLOCK
              value: {{ .Values.bitcoin.zmqPubHashBlock | default "tcp://0.0.0.0:8433" }}

            # Performance Tuning
            - name: DB_CACHE
              value: {{ .Values.bitcoin.dbCache | default "100" | quote }}
            - name: MAX_CONNECTIONS
              value: {{ .Values.bitcoin.maxConnections | default "20" | quote }}
            - name: RPC_WORK_QUEUE
              value: {{ .Values.bitcoin.rpcWorkQueue | default "8" | quote }}
            - name: MAX_MEMPOOL
              value: {{ .Values.bitcoin.maxMempool | default "50" | quote }}
            - name: BLOCK_RECONSTRUCTION_EXTRA_TXN
              value: {{ .Values.bitcoin.blockReconstructionExtraTxn | default "5000" | quote }}

            # OCEAN Policy Compliance
            - name: DATA_CARRIER_SIZE
              value: {{ .Values.bitcoin.dataCarrierSize | default "1" | quote }}
            - name: ACCEPT_NON_STD_TXN
              value: {{ .Values.bitcoin.acceptNonStdTxn | default "0" | quote }}
            - name: ACCEPT_NON_STD_DATA_CARRIER
              value: {{ .Values.bitcoin.acceptNonStdDataCarrier | default "0" | quote }}
            - name: DATA_CARRIER_COST
              value: {{ .Values.bitcoin.dataCarrierCost | default "1" | quote }}
            - name: DATACARRIERSIZE_LIMIT
              value: {{ .Values.bitcoin.dataCarrierSizeLimit | default "42" | quote }}
            - name: BYTES_PER_SIGOP
              value: {{ .Values.bitcoin.bytesPerSigop | default "20" | quote }}
            - name: BYTES_PER_SIGOP_STRICT
              value: {{ .Values.bitcoin.bytesPerSigopStrict | default "20" | quote }}
            - name: MAX_SCRIPT_SIZE
              value: {{ .Values.bitcoin.maxScriptSize | default "1650" | quote }}
            - name: MEMPOOL_FULL_RBF
              value: {{ .Values.bitcoin.mempoolFullRbf | default "1" | quote }}
            - name: MEMPOOL_REPLACEMENT
              value: {{ .Values.bitcoin.mempoolReplacement | default "fee,-optin" }}
            - name: MIN_RELAY_TX_FEE
              value: {{ .Values.bitcoin.minRelayTxFee | default "0.00001" | quote }}
            - name: PERMIT_BARE_MULTISIG
              value: {{ .Values.bitcoin.permitBareMultisig | default "0" | quote }}
            - name: PERMIT_BARE_PUBKEY
              value: {{ .Values.bitcoin.permitBarePubkey | default "0" | quote }}
            - name: REJECT_PARASITES
              value: {{ .Values.bitcoin.rejectParasites | default "1" | quote }}
            - name: SPK_REUSE
              value: {{ .Values.bitcoin.spkReuse | default "allow" }}

            # Mining Block Template
            - name: BLOCK_MAX_SIZE
              value: {{ .Values.bitcoin.blockMaxSize | default "3985000" | quote }}
            - name: BLOCK_MAX_WEIGHT
              value: {{ .Values.bitcoin.blockMaxWeight | default "3985000" | quote }}
            - name: BLOCK_MIN_TX_FEE
              value: {{ .Values.bitcoin.blockMinTxFee | default "0.00001" | quote }}
            - name: BLOCK_PRIORITY_SIZE
              value: {{ .Values.bitcoin.blockPrioritySize | default "0" | quote }}

            # Reindex flags
            - name: REINDEX
              value: {{ .Values.bitcoin.reindex | default "0" | quote }}
            - name: REINDEX_CHAINSTATE
              value: {{ .Values.bitcoin.reindexChainstate | default "0" | quote }}

          ports:
            - name: rpc
              containerPort: {{ .Values.global.service.ports.rpc }}
            - name: p2p
              containerPort: {{ .Values.service.ports.p2p }}
            - name: zmqpubrawtx
              containerPort: {{ .Values.service.ports.zmqpubrawtx }}
            - name: zmqpubrawblock
              containerPort: {{ .Values.service.ports.zmqpubrawblock }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: exporter
          image: ghcr.io/esomore/bitcoin-prometheus-exporter:master
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BITCOIN_RPC_HOST
            value: 127.0.0.1
          - name: BITCOIN_RPC_USER
            value: rpcuser
          - name: BITCOIN_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
                key: password
          - name: METRICS_PORT
            value: {{ .Values.service.ports.metrics | quote }}
          - name: BITCOIN_RPC_PORT
            value: {{ .Values.global.service.ports.rpc | quote }}
          ports:
          - name: metrics
            containerPort: {{ .Values.service.ports.metrics }}
      {{- if .Values.datum.enabled }}
        - name: datum
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.datum.image.repository }}:{{ .Values.datum.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.datum.image.pullPolicy }}
          env:
            - name: DATUM_RPCURL
              value: "http://{{ .Values.datum.bitcoin.rpcHost }}"
            - name: DATUM_RPCUSER
              value: "{{ .Values.datum.bitcoin.rpcuser }}"
            - name: DATUM_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
                  key: password
            - name: DATUM_POOL_ADDRESS
              value: "{{ .Values.datum.mining.address }}"
            - name: DATUM_COINBASE_TAG_PRIMARY
              value: "{{ .Values.datum.mining.coinbaseTagPrimary }}"
            - name: DATUM_COINBASE_TAG_SECONDARY
              value: "{{ .Values.datum.mining.coinbaseTagSecondary }}"
            - name: DATUM_POOL_HOST
              value: "{{ .Values.datum.mining.poolHost }}"
          ports:
            - name: stratum
              containerPort: 23334
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.datum.resources | nindent 12 }}
      {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoin.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}