apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.global.service.ports.rpc }}
    - name: p2p
      port: {{ .Values.service.ports.p2p }}
    - name: zmqpubrawtx
      port: {{ .Values.service.ports.zmqpubrawtx }}
    - name: zmqpubrawblock
      port: {{ .Values.service.ports.zmqpubrawblock }}
    - name: zmqpubhashblock
      port: {{ .Values.service.ports.zmqpubhashblock }}
    - name: datum
      port: {{ .Values.service.ports.datum }}
    - name: stratum
      port: {{ .Values.service.ports.stratum }}
  selector:
    {{- include "bitcoin.selectorLabels" . | nindent 4 }}
