apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bitcoin.fullname" . }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "bitcoin.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "bitcoin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "bitcoin.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      priorityClassName: {{ .Values.priorityClassName | default "" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitcoin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.extraInitContainers }}
      initContainers:
      {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 8 }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "bitcoin-cli stop"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          env:
            # Core Settings
            - name: SERVER_ENABLED
              value: {{ .Values.bitcoin.serverEnabled | default 1 | toString | quote }}
            - name: TXINDEX_ENABLED
              value: {{ .Values.bitcoin.txindexEnabled | default 1 | toString | quote }}
            - name: PRINTTOCONSOLE_ENABLED
              value: {{ .Values.bitcoin.printtoconsoleEnabled | default 1 | toString | quote }}
            - name: RPC_USER
              value: {{ .Values.bitcoin.rpcUser | default "rpcuser" | quote }}
            - name: RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
                  key: password
            - name: RPC_BIND
              value: {{ .Values.bitcoin.rpcBind | default "0.0.0.0" | quote }}
            - name: RPC_PORT
              value: {{ .Values.global.service.ports.rpc | default 8332 | toString | quote }}
            - name: RPC_ALLOW_IP
              value: {{ .Values.bitcoin.rpcAllowIP | default "0.0.0.0/0" | quote }}

            # ZMQ Settings
            - name: ZMQ_PUB_RAW_TX
              value: {{ .Values.bitcoin.zmqPubRawTx | default "tcp://0.0.0.0:8431" | quote }}
            - name: ZMQ_PUB_RAW_BLOCK
              value: {{ .Values.bitcoin.zmqPubRawBlock | default "tcp://0.0.0.0:8432" | quote }}
            - name: ZMQ_PUB_HASH_BLOCK
              value: {{ .Values.bitcoin.zmqPubHashBlock | default "tcp://0.0.0.0:8433" | quote }}

            # Performance Tuning
            - name: DB_CACHE
              value: {{ .Values.bitcoin.dbCache | default 100 | toString | quote }}
            - name: MAX_CONNECTIONS
              value: {{ .Values.bitcoin.maxConnections | default 20 | toString | quote }}
            - name: RPC_WORK_QUEUE
              value: {{ .Values.bitcoin.rpcWorkQueue | default 8 | toString | quote }}
            - name: MAX_MEMPOOL
              value: {{ .Values.bitcoin.maxMempool | default 50 | toString | quote }}
            - name: BLOCK_RECONSTRUCTION_EXTRA_TXN
              value: {{ .Values.bitcoin.blockReconstructionExtraTxn | default 5000 | toString | quote }}

            # OCEAN Policy Compliance
            - name: DATA_CARRIER_SIZE
              value: {{ .Values.bitcoin.dataCarrierSize | default 1 | toString | quote }}
            - name: ACCEPT_NON_STD_TXN
              value: {{ .Values.bitcoin.acceptNonStdTxn | default 0 | toString | quote }}
            - name: ACCEPT_NON_STD_DATA_CARRIER
              value: {{ .Values.bitcoin.acceptNonStdDataCarrier | default 0 | toString | quote }}
            - name: DATA_CARRIER_COST
              value: {{ .Values.bitcoin.dataCarrierCost | default 1 | toString | quote }}
            - name: DATACARRIERSIZE_LIMIT
              value: {{ .Values.bitcoin.dataCarrierSizeLimit | default 42 | toString | quote }}
            - name: BYTES_PER_SIGOP
              value: {{ .Values.bitcoin.bytesPerSigop | default 20 | toString | quote }}
            - name: BYTES_PER_SIGOP_STRICT
              value: {{ .Values.bitcoin.bytesPerSigopStrict | default 20 | toString | quote }}
            - name: MAX_SCRIPT_SIZE
              value: {{ .Values.bitcoin.maxScriptSize | default 1650 | toString | quote }}
            - name: MEMPOOL_FULL_RBF
              value: {{ .Values.bitcoin.mempoolFullRbf | default 1 | toString | quote }}
            - name: MEMPOOL_REPLACEMENT
              value: {{ .Values.bitcoin.mempoolReplacement | default "fee,-optin" | quote }}
            - name: MIN_RELAY_TX_FEE
              value: {{ printf "%.5f" (float64 (default 0.00001 .Values.bitcoin.minRelayTxFee)) | quote }}
            - name: PERMIT_BARE_MULTISIG
              value: {{ .Values.bitcoin.permitBareMultisig | default 0 | toString | quote }}
            - name: PERMIT_BARE_PUBKEY
              value: {{ .Values.bitcoin.permitBarePubkey | default 0 | toString | quote }}
            - name: REJECT_PARASITES
              value: {{ .Values.bitcoin.rejectParasites | default 1 | toString | quote }}
            - name: SPK_REUSE
              value: {{ .Values.bitcoin.spkReuse | default "allow" | quote }}

            # Mining Block Template
            - name: BLOCK_MAX_SIZE
              value: {{ printf "%.0f" (float64 (default 3985000 .Values.bitcoin.blockMaxSize)) | quote }}
            - name: BLOCK_MAX_WEIGHT
              value: {{ printf "%.0f" (float64 (default 3985000 .Values.bitcoin.blockMaxWeight)) | quote }}
            - name: BLOCK_MIN_TX_FEE
              value: {{ printf "%.5f" (float64 (default 0.00001 .Values.bitcoin.blockMinTxFee)) | quote }}
            - name: BLOCK_PRIORITY_SIZE
              value: {{ .Values.bitcoin.blockPrioritySize | default 0 | toString | quote }}

            # Reindex flags
            - name: REINDEX
              value: {{ .Values.bitcoin.reindex | default 0 | toString | quote }}
            - name: REINDEX_CHAINSTATE
              value: {{ .Values.bitcoin.reindexChainstate | default 0 | toString | quote }}

          ports:
            - name: rpc
              containerPort: {{ .Values.global.service.ports.rpc }}
            - name: p2p
              containerPort: {{ .Values.service.ports.p2p }}
            - name: zmqpubrawtx
              containerPort: {{ .Values.service.ports.zmqpubrawtx }}
            - name: zmqpubrawblock
              containerPort: {{ .Values.service.ports.zmqpubrawblock }}
          volumeMounts:
            - name: data
              mountPath: /data/.bitcoin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: exporter
          image: ghcr.io/esomore/bitcoin-prometheus-exporter:master
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BITCOIN_RPC_HOST
            value: 127.0.0.1
          - name: BITCOIN_RPC_USER
            value: rpcuser
          - name: BITCOIN_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-rpcpassword" (include "bitcoin.fullname" .) }}
                key: password
          - name: METRICS_PORT
            value: {{ .Values.service.ports.metrics | toString | quote }}
          - name: BITCOIN_RPC_PORT
            value: {{ .Values.global.service.ports.rpc | toString | quote }}
          ports:
          - name: metrics
            containerPort: {{ .Values.service.ports.metrics }}

      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        "helm.sh/resource-policy": keep
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
    {{- end }}
  {{- else }}
  # Note: When persistence is disabled, StatefulSet will use emptyDir for the data volume
  # This is handled by the volume definition in the pod template
  # No volumeClaimTemplates are needed in this case
  {{- end }}