{{- if not .Values.bitcoin.rpcPasswordSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datum.fullname" . }}-rpcpassword
  labels:
    {{- include "datum.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.bitcoin.rpcPassword | quote }}
{{- end }}