apiVersion: v1
kind: Service
metadata:
  name: {{ include "datum.fullname" . }}
  labels:
    {{- include "datum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.stratum }}
      targetPort: stratum
      protocol: TCP
      name: stratum
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "datum.selectorLabels" . | nindent 4 }}
