# Test values for chart testing
# Disable health checks since Bitcoin RPC won't be available during testing
healthChecks:
  enabled: false

# Use test mining configuration
mining:
  address: "bc1qtest123test123test123test123test123test123"
  poolHost: "test.pool.local"  # Dummy pool host for testing

# Override bitcoin RPC to use a test password that won't conflict
bitcoin:
  rpcPassword: "test-password-for-ct"