name: Generate Helm Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**/values.yaml'
      - 'charts/**/Chart.yaml'

permissions:
  contents: write

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Helm-docs
        uses: docker://jnorwood/helm-docs:v1.14.2
        with:
          entrypoint: helm-docs
          args: --chart-search-root=charts --template-files=README.md.gotmpl

      - name: Commit and push documentation changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "Chart documentation has been updated automatically."
            git add .
            git commit -m "docs: update chart documentation automatically"
            git push
          else
            echo "Chart documentation is already up to date."
          fi
